local DiscordLib = loadstring(game:HttpGet"https://raw.githubusercontent.com/dawid-scripts/UI-Libs/main/discord%20lib.txt")()

local win = DiscordLib:Window("KeylessHub")
local serv = win:Server("KeylessHub", "")
-- Universal
local Universal = serv:Channel("Universal")
Universal:Button("Infinite Yield", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()
DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Universal:Button("Dex Explorer", function()
    loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/Dex%20Explorer.txt"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Universal:Button("OwlHub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/CriShoux/OwlHub/master/OwlHub.txt"))();
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Universal:Button("Keyboard", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))();
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Universal:Button("UNC Test", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/unified-naming-convention/NamingStandard/main/UNCCheckEnv.lua", true))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Universal:Button("Fling All", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/zqyDSUWX"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
-- Bedwars
local Bedwars = serv:Channel("Bedwars")
Bedwars:Button("Vape V4", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua", true))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Bedwars:Button("Aurora", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/cocotv666/Aurora/refs/heads/main/Aurora_Loader'))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Bedwars:Button("Spectator", function()
    local FunnyPlayerSigma = game:GetService("Players").LocalPlayer
    local FunnyPlayerCharacter = FunnyPlayerSigma.character
    FunnyPlayerCharacter.parent = nil
    FunnyPlayerCharacter.HumanoidRootPart:Destroy()
    FunnyPlayerCharacter.parent = workspace 
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
-- Doors
local Doors = serv:Channel("Doors")
Doors:Button("Blackking", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/DarkDoorsKing/Doors/main/Main'))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Doors:Button("Exolution", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/ExolutionProject/Scripts/main/ExolutionPremiumHub.lua'))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Doors:Button("FFJI", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FFJ1/Roblox-Exploits/main/scripts/Loader.lua"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
-- MM2
local MM2 = serv:Channel("MM2")
MM2:Button("xHub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Au0yX/Community/main/XhubMM2"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
MM2:Button("MarsQQ", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/MarsInsanity/ScriptHubScripts/refs/heads/master/MM2%20Admin%20Panel"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
MM2:Button("GG-Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Farx11122/Dupess/main/SecondDupe"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
MM2:Button("Symphony Hub", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/ThatSick/ArrayField/main/SymphonyHub.lua'))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
-- Blox Fruits
local BloxFruits = serv:Channel("Blox Fruits")
BloxFruits:Button("Redz", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/REDzHUB/BloxFruits/main/redz9999"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
BloxFruits:Button("Ziner", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Tienvn123tkvn/Test/main/ZINERHUB.lua"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
BloxFruits:Button("Matsune", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Yatsuraa/Matsune/main/matsunehubv1.lua"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
-- Arsenal
local Arsenal = serv:Channel("Arsenal")
Arsenal:Button("quotas", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Insertl/QuotasHub/main/BETAv1.3"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Arsenal:Button("brew", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/borntodiekuv/KeybrewHub/main/Main"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
Arsenal:Button("tbaohub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/tbao143/thaibao/main/TbaoHubArsenal"))()
    DiscordLib:Notification("KeylessHub", "Executed Script Successfully!", "Okay!")
end)
